const starter=[{day:'Leg Day',exercise:'Leg press',sets:4,reps:10,weight:180},{day:'Chest Day',exercise:'Bench press',sets:3,reps:8,weight:135},{day:'Core / Abs',exercise:'Plank',sets:3,reps:1,weight:0}];
let workouts=JSON.parse(localStorage.getItem('ztime-workouts')||'null')||starter;
let goal=Number(localStorage.getItem('ztime-goal')||5);
const $=s=>document.querySelector(s);
function render(){const list=$('#workoutList');list.innerHTML='';workouts.forEach((w,i)=>{const li=document.createElement('li'),info=document.createElement('div'),title=document.createElement('p'),meta=document.createElement('small'),remove=document.createElement('button');title.textContent=w.exercise;meta.textContent=`${w.day} · ${w.sets} sets × ${w.reps} reps${w.weight?` · ${w.weight} lb`:''}`;remove.textContent='Remove';remove.type='button';remove.setAttribute('aria-label',`Remove ${w.exercise}`);remove.onclick=()=>{workouts.splice(i,1);save();};info.append(title,meta);li.append(info,remove);list.append(li)});const n=workouts.length;$('#workoutCount').textContent=`${n} ${n===1?'entry':'entries'}`;$('#heroSessions').textContent=n;$('#sessionStat').textContent=`${n} / ${goal}`;$('#sessionBar').style.width=Math.min(n/goal*100,100)+'%';const left=Math.max(goal-n,0);$('#goalText').textContent=left?`${left} more ${left===1?'session':'sessions'} will reach your goal.`:'Weekly goal reached. Keep going!';const volume=workouts.reduce((sum,w)=>sum+w.sets*w.reps*w.weight,0);$('#volumeStat').textContent=volume.toLocaleString()+' lb';}
function save(){localStorage.setItem('ztime-workouts',JSON.stringify(workouts));render()}
$('#workoutForm').addEventListener('submit',e=>{e.preventDefault();workouts.unshift({day:$('#day').value,exercise:$('#exercise').value.trim(),sets:Number($('#sets').value),reps:Number($('#reps').value),weight:Number($('#weight').value)});save();e.target.reset();$('#sets').value=3;$('#reps').value=10;$('#weight').value=0;$('#workoutMessage').textContent='Workout added to your progress.'});
const tracks=[['Intensity Boost','Thrash Squad'],['Blood Rush','Gym Fuel Mix'],['Deep Focus Beats','Study Mode']];let current=0,playing=false,timer;
function setTrack(n){current=(n+tracks.length)%tracks.length;$('#trackTitle').textContent=tracks[current][0];$('#trackArtist').textContent=tracks[current][1];document.querySelectorAll('[data-track]').forEach((b,i)=>b.classList.toggle('active',i===current));$('#trackBar').style.width='20%'}
function togglePlay(){playing=!playing;$('#play').textContent=playing?'❚❚':'▶';$('#play').setAttribute('aria-label',(playing?'Pause ':'Play ')+tracks[current][0]);clearInterval(timer);if(playing){let x=20;timer=setInterval(()=>{$('#trackBar').style.width=(x=x>=100?0:x+1)+'%'},350)}}
$('#play').onclick=togglePlay;$('#next').onclick=()=>setTrack(current+1);$('#previous').onclick=()=>setTrack(current-1);document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>setTrack(Number(b.dataset.track)));
const dialog=$('#profileDialog');$('#profileButton').onclick=()=>dialog.showModal();$('.close').onclick=()=>dialog.close();$('#profileForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#name').value.trim();goal=Number($('#goal').value);localStorage.setItem('ztime-name',name);localStorage.setItem('ztime-goal',goal);$('#profileButton').textContent=name;render();dialog.close()});const name=localStorage.getItem('ztime-name');if(name)$('#profileButton').textContent=name;
$('#postForm').addEventListener('submit',e=>{e.preventDefault();const article=document.createElement('article'),avatar=document.createElement('b'),content=document.createElement('div'),topic=document.createElement('small'),title=document.createElement('h3'),text=document.createElement('p');avatar.textContent='YOU';topic.textContent=$('#topic').value.toUpperCase();title.textContent=$('#postTitle').value.trim();text.textContent=$('#postBody').value.trim();content.append(topic,title,text);article.append(avatar,content);$('#posts').prepend(article);e.target.reset();$('#postMessage').textContent='Your discussion was posted in this demo.'});
setTrack(0);render();
